### PR TITLE
Update MD5

### PR DESCRIPTION
**Pull request by Igor-Palaguta**
Update to recent [MD5 sources](https://github.com/onmyway133/SwiftHash/blob/master/Sources/MD5.swift) to fix https://github.com/hyperoslo/Cache/issues/233

### CODE REVIEW

**Comment by naoya0731** [comment]
This is very important PR. 
I couldn't archive project until using this PR.

Version 10.2 beta 4 + Swift 4.2 + Cache 5.2.0

**Comment by Igor-Palaguta** [comment]
Can we merge it and bump new version if it is fine

Thanks

**Comment by piemonte** [comment]
@onmyway133 this is a helpful fix for an amazing lib, any chance it could be merged?

**Comment by JValldejuli** [comment]
This fixed building in Release with Whole Module compilation for me on Xcode 10.2 GM.

**Comment by weisso5** [comment]
Is the Tab change and Indent change really required for this ?

**Comment by Igor-Palaguta** [comment]
@weisso5 2 spaces a little unusual. So not to break formatting had to set 2 tabs for project

**Comment by olcayertas** [comment]
Why and how does this fix the #233 ? Really interesting.

**Comment by Igor-Palaguta** [comment]
@olcayertas issue in swift compiler

**Comment by onmyway133** [comment]
@Igor-Palaguta @piemonte Hi, I no longer maintain this project 😢

**Comment by enoelboostmi** [comment]
@onmyway133 Would you be interested in transferring or giving merge rights?

**Comment by piemonte** [comment]
@vadymmarkov hey there, would you still happen to have permissions to this amazing library? 🙏

**Comment by vadymmarkov** [comment]
Hey, unfortunately I don't have permissions.

**Comment by alexpersian** [comment]
Is there another maintainer for this project at Hyper, or has it been abandoned?

**Comment by aehlke** [comment]
Time for a community fork?

**Comment by yujiea** [comment]
Anyone can make a new release with this pull request? I also verified this, it works fine.

**Comment by vadymmarkov** [comment]
@onmyway133 Have you considered transferring Cache to your account or perhaps to a separate organization?

**Comment by weakfl** [comment]
@vadymmarkov maybe?

**Comment by zenangst** [comment]
I've been in talks with the peeps over at Hyper, I think they have an internal process going on what to do with the framework. Raised my hand as a volunteer maintainer for the project, let's see how it goes 😎

**Comment by vadymmarkov** [comment]
Doesn't really matter where it's located, but I'd love to have permissions as well 😉

**Comment by alexpersian** [comment]
@zenangst @onmyway133 any update here on transfer of ownership / continued maintenance of this library? On the fence about our team using this.

**Comment by zenangst** [comment]
Hey @alexpersian, I've sent the person in charge a message on Slack but so far it is radio silence. I'll give them another ping and keep you posted.

**Comment by aehlke** [comment]
@zenangst no word?

**Comment by zenangst** [comment]
Sadly no, I’ve reached out countless times. Will give it another go, fingers crossed.

**Comment by nickskull** [comment]
I can hardly understand why a PR with no conflicts that contains hotfix does not get merged.

**Comment by zenangst** [comment]
@nickskull the situation is a bit icky, we would love to help but it is basically up to the Hyper organization to decide what to do with the libraries. We would love to help maintain these things going forward but without any active decision being made by the organization to add us as maintainers or transfer of ownership, there isn't really that much we can do about it I'm afraid.

I sent them another nudge now, pointing to this discussion, hoping that it will speed things up.

**Comment by hyouuu** [comment]
If they keep not giving any response, I guess the only way forward is to decide on an agreed fork address and go from there?

**Comment by onmyway133** [comment]
@vadymmarkov I don't have permission to this repo either

**Comment by nickskull** [comment]
@zenangst I understand the situation, it's just strange to me how this decision can take so long in a company that's not a huge enterprise - maybe it's more about not wanting to make the decision. :D 

I suppose a fork would actually be a way forward, it is MIT licensed after all.

**Comment by alexpersian** [comment]
Has anyone taken on forking this yet to get it up to date with Swift 5 and Xcode 11?

**Comment by hyouuu** [comment]
@alexpersian - doesn't seem so... you want to take the lead? ;)

**Comment by zenangst** [comment]
What can I tell you, everything that I've been told by the people in charge has turned out to be empty promises. I've tried to gain access in order the take the project further but without any luck.
I'm so sorry that this happened 😞

**Comment by Neilfau** [comment]
So does the licence allow us to fork this or migrate it to a new repo with the permission of hyper?

**Comment by zenangst** [comment]
I'm no legal scholar but the way I read the following text should allow it:

```
Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), 
to deal in the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in 
all copies or substantial portions of the Software.
```

**Comment by alexpersian** [comment]
In an effort to prevent this library from dying I've forked the repo and will attempt to keep up with maintenance as best I can. Will welcome anyone else that's interested in helping as my OSS experience is limited. More than happy to add previous maintainers as repo owners, etc. (@zenangst?)
Feel free to migrate this and any other PR's over to the new fork so the library can be updated. I'll work to update the Cocoapods trunk as well.

https://github.com/alexpersian/Cache

**Comment by jnordberg** [comment]
Which fork is maintained then? Need a clickable link here people!

**Comment by malonehedges** [comment]
@3lvis can this be merged in?

**Comment by 3lvis** [comment]
@malonehedges https://github.com/hyperoslo/Cache/pull/262

**Pull request closed without merging**
