### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by MrAsterisco**
I have successfully converted the project to Swift 5. No changes to the source code were necessary, but I've run all unit tests on all platforms anyway: they all pass; to compile unit tests, though, I had to update a few constants in `TestHelper.swift`.

All warnings have been solved for all targets on Xcode, except for the `TARGETED_DEVICE_FAMILY` warning on the tvOS target, which I don't understand.

I've also managed to solve the compile issue, probably due to a bug in the Swift compiler. The solution involves changing the `Optimization Level` build option to `Optimize for Size` instead of `Optimize for Speed`. I successfully integrated the library into an existing app and I haven't seen any change in speed whatsoever. Maybe it's worth reporting this to Apple, using this project as a demonstration of the issue, which happens only when building in Release.

### CODE REVIEW

**Comment by djmixroman** [comment]
What kind of sh#t is going on with optimization level?

**Comment by bjarkehs** [comment]
Since you've pulled in the changes from Igor Palaguta, you don't need to have `-Osize` as optimization. I'm also not sure you need to change the indentation levels 😉

**Comment by AYastrebov** [comment]
Please, remove Result and use one built-in in swift 5

**Comment by mauhcs** [comment]
Is is safe to use this branch? 
Why wasn't it merged?

**Comment by colinhumber** [comment]
Bump

**Pull request closed without merging**
