### PR TITLE
Feature: data protection

### PR DESCRIPTION
**Pull request by vadymmarkov**
1) Simplify public API by removing `StorageFactory`. Memory cache will always be a front storage, and disk cache will be a back storage. Fixes https://github.com/hyperoslo/Cache/issues/79
2) Allow to specify data protection, so it's possible to protect files using on-disk encryption.
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html#//apple_ref/doc/uid/TP40007072-CH5-SW21 Fixes https://github.com/hyperoslo/Cache/issues/68
3) Change config to reflect new changes:
```swift
let config = Config(
  // Expiry date that will be applied by default for every added object
  // if it's not overridden in the add(key: object: expiry: completion:) method
  expiry: .date(Date().addingTimeInterval(100000)),
  /// Maximum amount of items to store in memory
  maxObjectsInMemory: 20,
  /// Maximum size of the disk cache storage (in bytes)
  maxDiskSize: 10000,
  // Where to store the disk cache. If nil, it is placed in an automatically generated directory in Caches
  cacheDirectory: NSSearchPathForDirectoriesInDomains(.documentDirectory,
                                                      FileManager.SearchPathDomainMask.userDomainMask,
                                                      true).first! + "/cache-in-documents",
  // Data protection is used to store files in an encrypted format on disk and to decrypt them on demand
  fileProtectionType: .complete
)
```

Since `Config` is changed it's a breaking change ⚠️

### CODE REVIEW

**Comment by zenangst** [comment]
What do you guys think about my comment about the version number? @JohnSundell @vadymmarkov @onmyway133 
Might seem odd to bump it before we know exactly what the new version will be, but it it is breaking then at least we know that it should be a new major version.

**Comment by vadymmarkov** [comment]
I didn't bump the version number, because I'm planning to make one more breaking change before we release 3.0.0.

**Comment by zenangst** [comment]
@vadymmarkov my point is that this new version is already not compatible with version 2.0.0. I might be wrong about this but we have been doing  some mistakes in the past by just making it a minor version bump because it took so long between breaking the API and doing a release (raises hand and mouths "guilty") 😎

**Comment by vadymmarkov** [comment]
Right, but I mean that the next release will be 3.0.0, I just want to gather a few changes and I'm not planning to release when this PR is merged.

**Comment by onmyway133** [comment]
@vadymmarkov interesting PR. If we specify protection level, does it have any effect on existing non-protection-level files?

**Comment by vadymmarkov** [comment]
@onmyway133 No, it adds protection level only on newly created files.

**Pull request merged**
