### PR TITLE
Project update

### PR DESCRIPTION
**Pull request by fassko**
* Swift 5 in podspec
* Swift 5 for project file
* fix warnings

### CODE REVIEW

**Comment by acegreen** [comment]
> It needs a new release for Swift PM to work.

You can grab it from master like such:
`.package(url: "https://github.com/fassko/Cache.git", .branch("master"))`

**Comment by fassko** [comment]
While this library owners are sleeping I got it working with SwiftPM and new Xcode using my account. :P

**Comment by fassko** [comment]
Hi @3lvis are you still supporting this library?

**Comment by 3lvis** [comment]
@fassko trying too, let's see how it goes!

**Comment by fassko** [comment]
Nice, I can help out. Because several of my apps use this library.

**Comment by 3lvis** [comment]
Glad to hear that! Thank you 🙌

**Pull request merged**
